### ISSUE TITLE
New scaleform - PAUSE MENU

### ISSUE THREAD

**Issue by SkyZ0347** [justalemon/LemonUI#39] opened 2021-08-29 19:32 UTC
![maxresdefault](https://user-images.githubusercontent.com/87867345/131262920-f3e7a598-37fd-42cb-b05b-7e543756d3a8.jpg)

A pause menu scaleform like on the image, as far as i remember but im not sure its created with some of these scaleforms:
Starting from https://vespura.com/fivem/scaleform/#PAUSE_MENU_BAR

But it might be for this instead, which will also be a nice to have in LemonUI

![image](https://user-images.githubusercontent.com/87867345/131263016-64bbbdc4-488c-4443-8a8a-963b752c9aee.png)

**Comment by justalemon** [comment] 2021-08-29 19:55
I think @Eddlm implemented the scaleform once as part of his mods. Ill probably ask him in the 5mods server about what info he has about the "session" scaleform (second picture).

**Comment by justalemon** [comment] 2021-08-29 19:57
Oh wait, dupe of #15

**Closed by justalemon** 2021-08-29 19:57 UTC
Labels: type: feature request, status: acknowledged, priority: p2 medium
